added Pagination and Swagger
OlegStashkiv/Online-Books-Store pull request #5
Opened 2023-09-07 19:15 UTC by OlegStashkiv

2023-09-08 00:39 UTC, Someboty approved these changes
Great work!

2023-09-08 18:11 UTC, Vasul-Pankiv requested changes

2023-09-08 18:11 UTC, Vasul-Pankiv commented on pom.xml
> +		</dependency>
delete one of them)

2023-09-11 14:26 UTC, vovasalyha approved these changes

2023-09-11 15:38 UTC, merged